---
codecov:
  notify:
    after_n_builds: 2  # Wait for all 3 flag uploads (integration, properties, unittests)
    wait_for_ci: true  # Wait for CI to complete before sending status
coverage:
  range: 90..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        flags:
          - properties
          - unittests
    patch:
      default:
        target: 90%
        threshold: 1%
ignore:
  - tests/**/*
