---
codecov:
  notify:
    after_n_builds: 2  # Wait for all 2 flag uploads (integration, properties, unittests)
    wait_for_ci: true  # Wait for CI to complete before sending status
coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        flags:
          - properties
          - unittests
    patch:
      default:
        target: auto
        threshold: 1%
flags:
  ai:
    paths:
      - src/
    carryforward: true
  dev:
    paths:
      - src/
    carryforward: true
comment:
  layout: flags, diff, files
  require_changes: false
  behavior: default
ignore:
  - tests/*
  - target/*
