---
services:
  relayer:
    container_name: openzeppelin-relayer
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.development}
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
        # Options: trace, debug, info, warn, error
        # Default: info
      - LOG_LEVEL=info
        # Options: stdout, file
        # Uncomment to write logs to file
        # Default: stdout
      #- LOG_MODE=file
        # Default: logs/relayer.log
        # Uncomment to specify log file path
      #- LOG_FILE=logs/relayer.log
    depends_on:
      - redis
    networks:
      - relayer-network
    restart: always
    volumes:
      - ./config:/app/config/:ro
      # Uncomment to persist logs
      # Default: writes to stdout
      #- ./logs:/app/logs

  redis:
    container_name: openzeppelin-relayer-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: [redis-server, --appendonly, yes, --save, '60', '1']
    networks:
      - relayer-network
    restart: always

networks:
  relayer-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
