version: '3.9'

services:
  relayer:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
    depends_on:
      - redis
    networks:
      - relayer-network
    restart: always
    volumes:
      - ./config.json:/app/config.json

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
    networks:
      - relayer-network
    restart: always

networks:
  relayer-network:
    driver: bridge

volumes:
  redis_data:
    driver: local