---
global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: openzeppelin-relayer
    # Prometheus uses this api path to scrape metrics from the relayer container
    metrics_path: /debug/metrics/scrape
    scheme: http
    static_configs:
      - targets:
          - openzeppelin-relayer:8081
