---
version: '3.9'

services:
  relayer:
    build:
      context: ../../
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080/tcp
    environment:
      REDIS_URL: redis://redis:6379
      CONFIG_PATH: config/config.json
      # Set `WEBHOOK_SIGNING_KEY` & `API_KEY` values in your .env file (recommended) and use that instead of hardcoding them here
      # To avoid accidentally committing sensitive information to your repository
      WEBHOOK_SIGNING_KEY: example-key
      API_KEY: example-123456
      # Options: trace, debug, info, warn, error
      # Default: info
      LOG_LEVEL: info
      # Options: stdout, file
      # Default: stdout
      LOG_MODE: file
      # Default: logs/
      LOG_FILE_PATH: logs/
      # Set max log file size to rotate to new log file
      # Only used if LOG_MODE is file
      # Default: 1GB (1073741824 bytes)
      LOG_MAX_SIZE: 1073741824
    security_opt:
      - no-new-privileges
    networks:
      - relayer-network
      - metrics-network
    volumes:
      - ./config:/app/config/
      # Mount logs folder to persist logs
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: on-failure:5


  redis:
    image: redis:bookworm
    ports:
      - 6379:6379/tcp
    security_opt:
      - no-new-privileges
    volumes:
      - redis_data:/data
    command: [redis-server, --appendonly, yes, --save, '60', '1']
    networks:
      - relayer-network
      - metrics-network
    restart: on-failure:5


networks:
  metrics-network:
    internal: true
  relayer-network:
    driver: bridge

volumes:
  redis_data:
    driver: local

secrets:
  api_key:
    environment: API_KEY
  webhook_signing_key:
    environment: WEBHOOK_SIGNING_KEY
