---
name: Cache
description: Caches cargo dependencies
inputs:
  components:
    description: Additional Rust components to install (comma separated). rustfmt and clippy are always included.
    required: false
    default: ''
outputs:
  cache-hit:
    description: Cache Hit
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: setup rust tool chain
      uses: dtolnay/rust-toolchain@1.86.0  # v1.86.0
      with:
        components: ${{ (inputs.components != '') && format('{0}, rustfmt, clippy', inputs.components) || 'rustfmt, clippy' }}

    - name: Install libsodium
      run: sudo apt-get update && sudo apt-get install -y libsodium-dev
      shell: bash

    - name: Restore cargo dependencies from cache
      uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3  # v2.7.7
      id: cache

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        run_install: false
        version: 10

    - name: Use node@22
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 22.18.0

    - name: Build launchtube plugin example
      run: |
        cd examples/launchtube-plugin-example/launchtube
        pnpm install
        pnpm run build
        cd ../..
      shell: bash
