---
site:
  title: OpenZeppelin Relayer
  start_page: openzeppelin-relayer:ROOT:index.adoc

content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs

asciidoc:
  attributes:
    idprefix: ''

ui:
  supplemental_files: supplemental-ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

urls:
  redirect_facility: netlify

output:
  dir: build/site

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        start_on_load: true
