name: Update Technical Docs Link

on:
  push:
    branches:
      - 'release-v*'
      - 'rust-docs'

jobs:
  update-docs-link:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5  # v2.0.2
        id: gh-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          token: ${{ steps.gh-app-token.outputs.token }}

      - name: Get version from Cargo.toml
        id: get_version
        run: |
          version=$(grep -A 5 "\[package\]" Cargo.toml | grep "^version" | cut -d'"' -f2)
          if [ -z "$version" ]; then
            echo "Version not found in Cargo.toml" >&2
            exit 1
          fi
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get the branch name
        id: get_branch
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update the technical docs link in the nav.adoc file
        run: |
          major_minor_version=$(echo "${{ steps.get_version.outputs.version }}" | cut -d'.' -f1,2)
          branch="${{ steps.get_branch.outputs.branch }}"
          echo "Major and minor version: $major_minor_version"
          echo "Branch: $branch"

          if [[ "$branch" == release-v* ]]; then
            echo "Updating the release branch"
            sed -i -E "s|(https://)[^/]*--openzeppelin-relayer\.netlify\.app|\1release-v${major_minor_version}--openzeppelin-relayer.netlify.app|g" docs/modules/ROOT/nav.adoc
          elif [[ "$branch" == rust-* ]]; then
            echo "Updating the test branch"
            sed -i '' -E "s|(https://)[^/]*openzeppelin-relayer\.netlify\.app|\1qest-v${short_version}--openzeppelin-relayer.netlify.app|g" modules/ROOT/pages/structure.adoc
          elif [[ "$branch" == docs-v* ]]; then
            echo "Updating the docs branch"
            sed -i -E "s|(https://)[^/]*--openzeppelin-relayer\.netlify\.app|\1docs-v${major_minor_version}--openzeppelin-relayer.netlify.app|g" docs/modules/ROOT/nav.adoc
          else
            echo "No matching release or docs related branch. Skipping update..."
          fi

      - name: Create Pull Request to update the technical docs version
        if: ${{ steps.get_branch.outputs.branch != '' }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "docs: update technical docs version in the quickstart.adoc file"
          body: Automatically generated PR to update technical docs version in the quickstart.adoc file.
          base: ${{ steps.get_branch.outputs.branch }}
          sign-commits: true
          commit-message: "docs: update technical docs version in the quickstart.adoc file"
